# Generated by Django 5.2.8 on 2025-12-02 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('duration', models.IntegerField(help_text='duration in hourse')),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='courses/')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('expersite', models.CharField(max_length=50)),
                ('Trainer_photo', models.ImageField(blank=True, null=True, upload_to='Trainers/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.course')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.trainer')),
            ],
        ),
    ]
